### ISSUE TITLE
[FEAT] Create initial spreadsheet via python

### ISSUE THREAD

**Issue by mikeysan** [Sammeeey/plzCrawler#10]
I already mentioned this suggestion in discord but thought I would go ahead and create this issue anyway.
After reading through your readme, I noticed one of the first steps is to create the excel sheet with some headings.

I was wondering if it may not be better to create the file as you run the program. Have the first thing that happens be the creation of the file. Here's a sample I found that may work.

```py
from openpyxl import Workbook

workbook = Workbook()
sheet = workbook.active

sheet["A1"] = "hello"
sheet["B1"] = "world!"

workbook.save(filename="hello_world.xlsx")
```
What do you think?

**Comment by Sammeeey** [comment]
That's an interesting suggestion.👌
Thank you @mikeysan 

### clarification and explanation
As far as I understand you are referring to step 2 of the [installation & preparation](https://github.com/Sammeeey/plzCrawler#installation--preparation), right?

The original purpose of the project was a quite narrow scope:
Usually someone would have an excel sheet which already includes the listed *table columns* (see installation & preparation > 2 > ii. Table columns).
It would look similar to [sample spreadsheet](https://github.com/Sammeeey/plzCrawler/blob/5ad7f62800459fa8c3a01e2389d745ded169353d/example_spreadsheets/plzBeispielTabelle.xlsx) - a spreadsheet with all columns filled in but the PLZ (zipcode) column empty.

The scope of the plzCrawler tool is to complete the above mentioned table (or any other table which has an empty zipcode column) by finding the zip codes based on the street name, house number and city.

The result for the sample spreadsheet would be the [*plzBeispielTabelle-Ziel.xlsx*](https://github.com/Sammeeey/plzCrawler/blob/5ad7f62800459fa8c3a01e2389d745ded169353d/example_spreadsheets/plzBeispielTabelle-Ziel.xlsx).

### to make a long story short (less detailed, less technical)
If I understand your suggestion correctly, then I think that it doesn't fit in the current/original scope of the project (so far), since the plzCrawler tool only covers a very narrow field of application.
Originally it was only designed to cover one specific task - to fill in the empty zip codes.
But it doesn't necessarily need to remain in that narrow scope.

**If you have further ideas where something like this could be useful, then feel welcome to share them here**.🤗
I would love to make this project eventually useful again by implementing your ideas for a broader field of application.😊

Please correct me if I got something wrong about your idea.🤔

**Comment by mikeysan** [comment]
Yes. You are correct. I understand it better now. I had initially thought you were creating a blank spreadsheet and filling in the headers and THEN using code to get the rest of the data.

However, if you already have a spreadsheet with some data and are using code to get the zip then it makes sense that you wouldn't be creating the file again :)
